version: "3.5"
services:
    mysql:
        image: mariadb:latest
        restart: on-failure
        container_name: gaboot-shop-database
        environment:
            MYSQL_ROOT_PASSWORD: gaboot
            MYSQL_DATABASE: gaboot
            MYSQL_USER: docker
            MYSQL_PASSWORD: gaboot
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
            - ./out/dump:/var/www/public
    gaboot-api:
        build: .
        container_name: gaboot-shop-server
        environment:
            MYSQL_HOST: "mysql"
        expose:
            - 8080:8080
        depends_on:
            - mysql
        volumes:
            - ./out/Gaboot:/var/www/public
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8556:8000"
        restart: unless-stopped
        volumes:
            - "/mnt/k/Coding/2024/Gaboot Shop/gaboot-shop-backends/nginx/default.conf:/mnt/k/Coding/2024/Gaboot Shop/gaboot-shop-backends/etc/nginx/conf.d/default.conf"
            - ./app:/var/www/public
        depends_on:
            - gaboot-api
