version: "3.5"
services:
     gaboot-database:
        image: mariadb:latest
        restart: on-failure
        container_name: gaboot-shop-database
        environment:
            MYSQL_ROOT_PASSWORD: gaboot
            MYSQL_DATABASE: gaboot
            MYSQL_USER: docker
            MYSQL_PASSWORD: gaboot
        ports:
            - 3316:3306
        expose:
            - 3306
        networks:
            - gaboot
        volumes:
            - ./dump:/var/lib/mysql
     gaboot-api:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: gaboot-shop-server
        restart: unless-stopped
        init: true
        ports:
            - 5000:8080
        depends_on:
            - gaboot-database
        networks:
            - gaboot
        links:
            - gaboot-database
        volumes:
            - ./build/Linux-x64/uploads:/usr/local/bin/gaboot/uploads
            - ./build/Linux-x64/Drogon Log:/usr/local/bin/gaboot/Drogon Log
            - ./build/Linux-x64/Service:/var/log/
networks:
   gaboot:
    driver: bridge