version: "3.5"
services:
     gaboot-api:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: gaboot-shop-server
        restart: unless-stopped
        init: true
        ports:
            - 5000:8080
        env_file:
          - path: .env
            required: true
        networks:
            - database_gaboot
        volumes:
            - ./container/uploads:/home/skript023/gbt-backend/Linux/uploads/
            - ./container/DrogonLog:/home/skript023/gbt-backend/Linux/DrogonLog/
            - ./container/Service:/var/log/
networks:
   database_gaboot:
      external: true