version: "3.5"
services:
     mysql:
        image: mariadb:latest
        restart: on-failure
        container_name: gaboot-shop-database
        environment:
            MYSQL_ROOT_PASSWORD: gaboot
            MYSQL_DATABASE: gaboot
            MYSQL_USER: docker
            MYSQL_PASSWORD: gaboot
        ports:
            - 3316:3306
        expose:
            - 3306
        volumes:
            - ./out/dump:/var/lib/mysql
     gaboot-api:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: gaboot-shop-server
        init: true
        ports:
            - 5000:8080
        depends_on:
            - mysql
        volumes:
            - ./out/build/Linux-x64/uploads:/usr/local/bin/gaboot/uploads
            - ./out/build/Linux-x64/Drogon Log:/usr/local/bin/gaboot/Drogon Log
            - ./out/build/Linux-x64/Service:/var/log/
     #nginx:
        #image: nginx:latest
        #container_name: nginx
        #ports:
            #- "8556:8000"
        #restart: unless-stopped
        #volumes:
            #- "./nginx/default.conf:/mnt/k/Coding/2024/Gaboot Shop/gaboot-shop-backends/etc/nginx/conf.d/default.conf"
        #depends_on:
            #- gaboot-api
