version: "3.5"
services:
     gaboot-api:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: gaboot-shop-server
        restart: on-failure
        init: true
        ports:
            - 5000:8080
        depends_on:
            - gaboot-database
        networks:
            - gaboot
        links:
            - gaboot-database
        volumes:
            - ./container/uploads:/home/skript023/gbt-backend/Linux/uploads/
            - ./container/DrogonLog:/home/skript023/gbt-backend/Linux/DrogonLog/
            - ./container/Service:/var/log/
networks:
   gaboot:
    driver: bridge