//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "login.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string login::genText(const DrTemplateData& login_view_data)
{
	drogon::OStringStream login_tmp_stream;
	std::string layoutName{""};
	login_tmp_stream << "<!DOCTYPE html>\n";
	login_tmp_stream << "<html lang=\"en\">\n";
	login_tmp_stream << "<head>\n";
	login_tmp_stream << "  <meta charset=\"utf-8\"/>\n";
	login_tmp_stream << "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\n";
	login_tmp_stream << "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"/>\n";
	login_tmp_stream << "  <meta name=\"description\" content=\"\"/>\n";
	login_tmp_stream << "  <meta name=\"author\" content=\"\"/>\n";
	login_tmp_stream << "  <title>Admin Only</title>\n";
	login_tmp_stream << "  <!-- loader-->\n";
	login_tmp_stream << "  <link href=\"assets/css/pace.min.css\" rel=\"stylesheet\"/>\n";
	login_tmp_stream << "  <script src=\"assets/js/pace.min.js\"></script>\n";
	login_tmp_stream << "  <!--favicon-->\n";
	login_tmp_stream << "  <link rel=\"icon\" href=\"assets/images/favicon.ico\" type=\"image/x-icon\">\n";
	login_tmp_stream << "  <!-- Bootstrap core CSS-->\n";
	login_tmp_stream << "  <link href=\"assets/css/bootstrap.min.css\" rel=\"stylesheet\"/>\n";
	login_tmp_stream << "  <!-- animate CSS-->\n";
	login_tmp_stream << "  <link href=\"assets/css/animate.css\" rel=\"stylesheet\" type=\"text/css\"/>\n";
	login_tmp_stream << "  <!-- Icons CSS-->\n";
	login_tmp_stream << "  <link href=\"assets/css/icons.css\" rel=\"stylesheet\" type=\"text/css\"/>\n";
	login_tmp_stream << "  <!-- Custom Style-->\n";
	login_tmp_stream << "  <link href=\"assets/css/app-style.css\" rel=\"stylesheet\"/>\n";
	login_tmp_stream << "  \n";
	login_tmp_stream << "</head>\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "<body class=\"bg-theme bg-theme1\">\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "<!-- start loader -->\n";
	login_tmp_stream << "   <div id=\"pageloader-overlay\" class=\"visible incoming\"><div class=\"loader-wrapper-outer\"><div class=\"loader-wrapper-inner\" ><div class=\"loader\"></div></div></div></div>\n";
	login_tmp_stream << "   <!-- end loader -->\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "<!-- Start wrapper-->\n";
	login_tmp_stream << " <div id=\"wrapper\">\n";
login_tmp_stream<<"\n";
	login_tmp_stream << " <div class=\"loader-wrapper\"><div class=\"lds-ring\"><div></div><div></div><div></div><div></div></div></div>\n";
	login_tmp_stream << "	<div class=\"card card-authentication1 mx-auto my-5\">\n";
	login_tmp_stream << "		<div class=\"card-body\">\n";
	login_tmp_stream << "		 <div class=\"card-content p-2\">\n";
	login_tmp_stream << "		 	<div class=\"text-center\">\n";
	login_tmp_stream << "		 		<img src=\"assets/images/logo-icon.png\" alt=\"logo icon\">\n";
	login_tmp_stream << "		 	</div>\n";
	login_tmp_stream << "		  <div class=\"card-title text-uppercase text-center py-3\">Sign In</div>\n";
	login_tmp_stream << "		    <form>\n";
	login_tmp_stream << "			  <div class=\"form-group\">\n";
	login_tmp_stream << "			  <label for=\"exampleInputUsername\" class=\"sr-only\">Username</label>\n";
	login_tmp_stream << "			   <div class=\"position-relative has-icon-right\">\n";
	login_tmp_stream << "				  <input type=\"text\" id=\"exampleInputUsername\" class=\"form-control input-shadow\" placeholder=\"Enter Username\">\n";
	login_tmp_stream << "				  <div class=\"form-control-position\">\n";
	login_tmp_stream << "					  <i class=\"icon-user\"></i>\n";
	login_tmp_stream << "				  </div>\n";
	login_tmp_stream << "			   </div>\n";
	login_tmp_stream << "			  </div>\n";
	login_tmp_stream << "			  <div class=\"form-group\">\n";
	login_tmp_stream << "			  <label for=\"exampleInputPassword\" class=\"sr-only\">Password</label>\n";
	login_tmp_stream << "			   <div class=\"position-relative has-icon-right\">\n";
	login_tmp_stream << "				  <input type=\"password\" id=\"exampleInputPassword\" class=\"form-control input-shadow\" placeholder=\"Enter Password\">\n";
	login_tmp_stream << "				  <div class=\"form-control-position\">\n";
	login_tmp_stream << "					  <i class=\"icon-lock\"></i>\n";
	login_tmp_stream << "				  </div>\n";
	login_tmp_stream << "			   </div>\n";
	login_tmp_stream << "			  </div>\n";
	login_tmp_stream << "			<div class=\"form-row\">\n";
	login_tmp_stream << "			 <div class=\"form-group col-6\">\n";
	login_tmp_stream << "			   <div class=\"icheck-material-white\">\n";
	login_tmp_stream << "                <input type=\"checkbox\" id=\"user-checkbox\" checked=\"\" />\n";
	login_tmp_stream << "                <label for=\"user-checkbox\">Remember me</label>\n";
	login_tmp_stream << "			  </div>\n";
	login_tmp_stream << "			 </div>\n";
	login_tmp_stream << "			 <div class=\"form-group col-6 text-right\">\n";
	login_tmp_stream << "			  <a href=\"reset-password.html\">Reset Password</a>\n";
	login_tmp_stream << "			 </div>\n";
	login_tmp_stream << "			</div>\n";
	login_tmp_stream << "			 <button type=\"button\" class=\"btn btn-light btn-block\">Sign In</button>\n";
	login_tmp_stream << "			  <div class=\"text-center mt-3\">Sign In With</div>\n";
	login_tmp_stream << "			  \n";
	login_tmp_stream << "			 <div class=\"form-row mt-4\">\n";
	login_tmp_stream << "			  <div class=\"form-group mb-0 col-6\">\n";
	login_tmp_stream << "			   <button type=\"button\" class=\"btn btn-light btn-block\"><i class=\"fa fa-facebook-square\"></i> Facebook</button>\n";
	login_tmp_stream << "			 </div>\n";
	login_tmp_stream << "			 <div class=\"form-group mb-0 col-6 text-right\">\n";
	login_tmp_stream << "			  <button type=\"button\" class=\"btn btn-light btn-block\"><i class=\"fa fa-twitter-square\"></i> Twitter</button>\n";
	login_tmp_stream << "			 </div>\n";
	login_tmp_stream << "			</div>\n";
	login_tmp_stream << "			 \n";
	login_tmp_stream << "			 </form>\n";
	login_tmp_stream << "		   </div>\n";
	login_tmp_stream << "		  </div>\n";
	login_tmp_stream << "		  <div class=\"card-footer text-center py-3\">\n";
	login_tmp_stream << "		    <p class=\"text-warning mb-0\">Do not have an account? <a href=\"register.html\"> Sign Up here</a></p>\n";
	login_tmp_stream << "		  </div>\n";
	login_tmp_stream << "	     </div>\n";
	login_tmp_stream << "    \n";
	login_tmp_stream << "     <!--Start Back To Top Button-->\n";
	login_tmp_stream << "    <a href=\"javaScript:void();\" class=\"back-to-top\"><i class=\"fa fa-angle-double-up\"></i> </a>\n";
	login_tmp_stream << "    <!--End Back To Top Button-->\n";
	login_tmp_stream << "	\n";
	login_tmp_stream << "	<!--start color switcher-->\n";
	login_tmp_stream << "   <div class=\"right-sidebar\">\n";
	login_tmp_stream << "    <div class=\"switcher-icon\">\n";
	login_tmp_stream << "      <i class=\"zmdi zmdi-settings zmdi-hc-spin\"></i>\n";
	login_tmp_stream << "    </div>\n";
	login_tmp_stream << "    <div class=\"right-sidebar-content\">\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "      <p class=\"mb-0\">Gaussion Texture</p>\n";
	login_tmp_stream << "      <hr>\n";
	login_tmp_stream << "      \n";
	login_tmp_stream << "      <ul class=\"switcher\">\n";
	login_tmp_stream << "        <li id=\"theme1\"></li>\n";
	login_tmp_stream << "        <li id=\"theme2\"></li>\n";
	login_tmp_stream << "        <li id=\"theme3\"></li>\n";
	login_tmp_stream << "        <li id=\"theme4\"></li>\n";
	login_tmp_stream << "        <li id=\"theme5\"></li>\n";
	login_tmp_stream << "        <li id=\"theme6\"></li>\n";
	login_tmp_stream << "      </ul>\n";
login_tmp_stream<<"\n";
	login_tmp_stream << "      <p class=\"mb-0\">Gradient Background</p>\n";
	login_tmp_stream << "      <hr>\n";
	login_tmp_stream << "      \n";
	login_tmp_stream << "      <ul class=\"switcher\">\n";
	login_tmp_stream << "        <li id=\"theme7\"></li>\n";
	login_tmp_stream << "        <li id=\"theme8\"></li>\n";
	login_tmp_stream << "        <li id=\"theme9\"></li>\n";
	login_tmp_stream << "        <li id=\"theme10\"></li>\n";
	login_tmp_stream << "        <li id=\"theme11\"></li>\n";
	login_tmp_stream << "        <li id=\"theme12\"></li>\n";
	login_tmp_stream << "		<li id=\"theme13\"></li>\n";
	login_tmp_stream << "        <li id=\"theme14\"></li>\n";
	login_tmp_stream << "        <li id=\"theme15\"></li>\n";
	login_tmp_stream << "      </ul>\n";
	login_tmp_stream << "      \n";
	login_tmp_stream << "     </div>\n";
	login_tmp_stream << "   </div>\n";
	login_tmp_stream << "  <!--end color switcher-->\n";
	login_tmp_stream << "	\n";
	login_tmp_stream << "	</div><!--wrapper-->\n";
	login_tmp_stream << "	\n";
	login_tmp_stream << "  <!-- Bootstrap core JavaScript-->\n";
	login_tmp_stream << "  <script src=\"assets/js/jquery.min.js\"></script>\n";
	login_tmp_stream << "  <script src=\"assets/js/popper.min.js\"></script>\n";
	login_tmp_stream << "  <script src=\"assets/js/bootstrap.min.js\"></script>\n";
	login_tmp_stream << "	\n";
	login_tmp_stream << "  <!-- sidebar-menu js -->\n";
	login_tmp_stream << "  <script src=\"assets/js/sidebar-menu.js\"></script>\n";
	login_tmp_stream << "  \n";
	login_tmp_stream << "  <!-- Custom scripts -->\n";
	login_tmp_stream << "  <script src=\"assets/js/app-script.js\"></script>\n";
	login_tmp_stream << "  \n";
	login_tmp_stream << "</body>\n";
	login_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(login_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = login_view_data;
auto str = std::move(login_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
