name: build

on: [push, pull_request]

env:
  VCPKG_FOLDER: ./vcpkg

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3

      # Add other necessary steps like installing dependencies, building, etc.

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/Gaboot-dev-${GITHUB_SHA}.exe

  upload_to_vps:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: binary
          path: build/

      - name: Upload Artifact to VPS
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem
          scp -i ssh_key.pem -o StrictHostKeyChecking=no build/Gaboot-dev-${GITHUB_SHA}.exe ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/skript023/gbt-backend/Linux/
