name: build

on: [push, pull_request]

env:
  VCPKG_FOLDER: ./vcpkg

jobs:
  build:
    runs-on: windows-2022
    name: build
    steps:
      - uses: actions/checkout@v3

      - name: Check CMake version
        run: cmake --version

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect
          conan profile show -s:a settings.arch=x86_64 default
          conan profile show -s:a settings.build_type=Release default
          conan profile show -s:a settings.compiler=msvc default
          conan profile show -s:a settings.compiler.cppstd=20 default
          conan profile show -s:a settings.compiler.runtime=dynamic default
          conan profile show -s:a settings.compiler.version=193 default
          conan profile show -s:a settings.os=Windows default
          conan profile show -c:a tools.cmake.cmaketoolchain:generator=Ninja

      - name: Install Package
        run: conan install conanfile.txt -of=conan/Windows --build=missing

      - name: Remove CMakeUserPresets.json
        run: rm CMakeUserPresets.json
          
      - name: Setup vcpkg toolchain
        run: cmake -D CMAKE_BUILD_TYPE=Release -S. -Bbuild -G Ninja
        
      - name: Build 64bit release Executable
        run: cmake --build ./build --config Release --target Gaboot --

      - name: Check if Executable got built
        run: if (-Not (Test-Path -path "build/Gaboot.exe")) {throw 1}

      - name: Rename Executable to Gaboot-dev-{GITHUB_SHA}.exe
        run: |
          del Gaboot-dev-*.exe
          ren Gaboot.exe Gaboot-dev-${{github.sha}}.exe
        working-directory: build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/Gaboot-dev-*.exe
