name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    name: build
    steps:
      - uses: actions/checkout@v3

      - name: Check CMake version
        run: cmake --version

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Install Conan
        run: |
          pip install conan==2.2.2
          conan config install https://bitbucket.org/telkom-workspace/gaboot-backend/downloads/config.zip

      - name: Install Package
        run: conan install conanfile.py -of=conan/Windows --build=missing

      - name: Remove CMakeUserPresets.json
        run: rm CMakeUserPresets.json
          
      - name: Setup vcpkg toolchain
        run: cmake -D CMAKE_BUILD_TYPE=Release -S. -Bbuild -G Ninja
        
      - name: Build 64bit release Executable
        run: cmake --build ./build --config Release --target Gaboot --

      - name: Check if Executable got built
        run: if (-Not (Test-Path -path "build/Gaboot.exe")) {throw 1}

      - name: Zip Multiple Files
        run: |
          $paths = @(
            "build/Gaboot.exe",
            "./Dockerfile"
            "./docker-compose.yml"
          )
          Compress-Archive -Path $paths -DestinationPath build/Gaboot-windows-x64.zip

      - name: Rename Executable to Gaboot-dev-{GITHUB_SHA}.exe
        run: |
          del Gaboot-dev-*.exe
          ren Gaboot.exe Gaboot-dev-${{github.sha}}.exe
        working-directory: build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gaboot-backend
          path: build/Gaboot-dev-*.exe

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Gaboot-windows-x64.zip
          tag: v1.0.0
          asset_name: Gaboot-windows-x64.zip
          overwrite: true
          body: "Gaboot Release Binary"
          repo_name: skript023/Gaboot
